### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fusionneur**

### CODE REVIEW

**Comment by SuspensionPoint** [comment]
Is this still a working fork?

**Comment by fusionneur** [comment]
this is a pull request to update readme, nothing more. It is pending approval to merge.

**Comment by SuspensionPoint** [comment]
Yeah, I get that. I just made the assumption that since you submitted a PR that you might also be knowledgeable of if this is still a working technique.

I'm on windows and I've tried running the patch.bat script a few different times on various api versions / android emulators created via the AVD Manager, with no success.

The closest I can get is a working ramdisk.img that when replaced provides the emulator with an installed Magisk Manager that has not successfully been rooted.

Do you happen to know if there is more steps to the process of rooting the emulator asides from those that are present in the ReadMe?

Thanks for responding!

**Comment by fusionneur** [comment]
Yes the script should still work. Can you please open a separeate issue related to this so that we can take a look.
Please provide as much info as you can to ease the investigation. Cheers

**Comment by SuspensionPoint** [comment]
Will do! Ty

**Pull request merged**
