### PR TITLE
Support for APK format of Magisk flashable zip

### PR DESCRIPTION
**Pull request by HemanthJabalpuri**
@shakalaca

### CODE REVIEW

**Comment by HemanthJabalpuri** [comment]
I am not sure how to handle `magisk[32|64]` binaries.

**Comment by shakalaca** [comment]
no problems, I'll test this week :)

**Comment by shakalaca** [comment]
I'll fix the 64bit issue later

**Comment by shakalaca** [comment]
verified on Android R, Q, O (x86 & x86_64)

**Pull request merged**
